### Pandas - Dataframe and Series

Pandas is a powerful data manipulation library in python,
widely used for data analysis and data cleaninng and handling structured data(tables).
It provides two primary data structures:
1) Series -1D (like one -> column)
2) DataFrame -2D (like a full table, multiple -> rows + columns)

A Series is a 
one-dimensional(1D - like a single column in excel/table)
labeled(each value or element has an index) array-like object, 
can hold different data types but internally prefer the uniform data-types.

While a DataFrame is a two-dimensional(2D - rows,columns like excel or full table) 
labeled table (columns has names and rows has indices),
size-mutable(rows, columns can be added or removed) and 
potentially heterogenous(different column can have different data types) 
tabular data stucture with labeled-axes (2 axes -> rows and columns has index and names).


In DataFrame's Each column is a Series
Series -> one axis labeled
DataFrame -> two axes labeled

In [2]:
import pandas as pd

### Series (column)

In [ ]:
### Series
# a pandas series is a one dimensional array-like object that can hold any datatype but usually uniform datatypes.
# it is similar to a column in a table.
import pandas as pd
data = [1,2,3,4,5]

series = pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [ ]:
## create a series from dictionary
data = {'a':1, 'b':2, 'c':3, 'd':4} # the keys will become the index
series = pd.Series(data)
print(series)

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
# index can be created like this way as well :)
data = [10,20,30]
index = ['abs','bcd','cde']
series = pd.Series(data,index)
print(series)

abs    10
bcd    20
cde    30
dtype: int64

### DataFrames (rows+columns)

In [31]:
### Dataframes
# create a basic dataframe from a dictionary of list
data = {
    'Name': ['krish', 'farabe', 'jhon'],
    'Age': [32,25,45],
    'City': ['Bangalore', 'Mymensingh', 'Florida']
}
dataframe = pd.DataFrame(data)
print(dataframe)
print(type(dataframe))

     Name  Age        City
0   krish   32   Bangalore
1  farabe   25  Mymensingh
2    jhon   45     Florida
<class 'pandas.DataFrame'>

In [ ]:
## we can also conver dataframes to 2D array
import numpy as np
print(np.array(dataframe))

[['krish' 32 'Bangalore']
 ['farabe' 25 'Mymensingh']
 ['jhon' 45 'Florida']]

In [76]:
### create a dataframe from list of dictionary'
data = [
    {'name':'farabe', 'age': 25, 'city': 'Mymensingh'},
    {'name':'krish', 'age': 32, 'city': 'Bangalore'},
    {'name':'jhon', 'age': 45, 'city': 'Florida'}
]

dataframe = pd.DataFrame(data)
print(dataframe)

     name  age        city
0  farabe   25  Mymensingh
1   krish   32   Bangalore
2    jhon   45     Florida

In [7]:
### Opening a csv file as DataFrame

df = pd.read_csv('people-100.csv')
#print(df.head(5))
df.head(5)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [13]:
df.tail(5)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954-07-30,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932-04-29,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994-12-28,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012-04-12,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016-11-15,IT sales professional

In [28]:
### accessing the data from DataFrame

dataframe

     name  age        city
0  farabe   25  Mymensingh
1   krish   32   Bangalore
2    jhon   45     Florida

In [ ]:
# acces the 'name' column-index of the dataframe
dataframe['name']

0    farabe
1     krish
2      jhon
Name: name, dtype: str

In [ ]:
type(dataframe['name'])
# see when we pick a single column it actually becomes a Series.

pandas.Series

In [ ]:
# 1. acces the dataframe element using df.loc[r_label, col_label]
### label-base indexing
print(dataframe.loc[0:, 'age'])

0    25
1    32
2    45
Name: age, dtype: int64

What it means:

0 → row label

'age' → column name

In [ ]:
# 2. acces the dataframe element using df.iloc[r_index, col_index]
print(dataframe.iloc[0:, 1:])

   age        city
0   25  Mymensingh
1   32   Bangalore
2   45     Florida

In [ ]:
### Accessing a specified element using .at
dataframe

     name  age        city
0  farabe   25  Mymensingh
1   krish   32   Bangalore
2    jhon   45     Florida

In [52]:
dataframe.at[2,'name']

'jhon'

In [53]:
### Accessing a specified element using .iat
dataframe.iat[2,2]

'Florida'

### Data Manipulation with DataFrame

In [54]:
dataframe

     name  age        city
0  farabe   25  Mymensingh
1   krish   32   Bangalore
2    jhon   45     Florida

In [65]:
### adding a new column
dataframe['salary'] = [1000,2000,3000]
dataframe

     name  age        city  salary
0  farabe   25  Mymensingh    1000
1   krish   32   Bangalore    2000
2    jhon   45     Florida    3000

In [56]:
### remove a column
dataframe.drop('salary')

KeyError: "['salary'] not found in axis"

KeyError: "['salary'] not found in axis"
axis = (row_index,column_index)
by default df.drop() removes rows, not columns.
dataframe.drop('salary', axis=0) # here axis=0 means delete a row labeled/indexed with 'salary'
where we see there are no 'salary' index in the rows.

so we modify it as following:
dataframe.drop('salary', axis=1)
axis = 1 means delete coulumn = 'salary'

In [66]:
dataframe.drop('salary', axis=1)

     name  age        city
0  farabe   25  Mymensingh
1   krish   32   Bangalore
2    jhon   45     Florida

In [67]:
dataframe

     name  age        city  salary
0  farabe   25  Mymensingh    1000
1   krish   32   Bangalore    2000
2    jhon   45     Florida    3000

the drop doest not save the result permanantly.
to permanantly delete we need to do the following:
dataframe.drop('salary', axis=1, implace=True)
or,
df = df.drop()

In [68]:
dataframe.drop('salary', axis=1, inplace=True)

In [69]:
dataframe

     name  age        city
0  farabe   25  Mymensingh
1   krish   32   Bangalore
2    jhon   45     Florida

In [ ]:
### add a num to every element of a column
dataframe['age']+=1

In [71]:
dataframe

     name  age        city
0  farabe   26  Mymensingh
1   krish   33   Bangalore
2    jhon   46     Florida

In [72]:
### drop a row
dataframe.drop(0)

    name  age       city
1  krish   33  Bangalore
2   jhon   46    Florida

In [73]:
dataframe

     name  age        city
0  farabe   26  Mymensingh
1   krish   33   Bangalore
2    jhon   46     Florida

In [77]:
dataframe.drop(0,inplace=True)

In [78]:
dataframe

    name  age       city
1  krish   32  Bangalore
2   jhon   45    Florida

In [79]:
df.head(5)

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,Shelby,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,Phillip,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,Kristine,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,Yesenia,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,Lori,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [9]:
#display the data types of each column
print(df.dtypes)

Index            int64
User Id            str
First Name         str
Last Name          str
Sex                str
Email              str
Phone              str
Date of birth      str
Job Title          str
dtype: object

In [ ]:
#describe the DataFrame gives the statistical calculations for the numerical columns.
print(df.describe())

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000