### Data Manipulation and Analysis with pandas

Data manipulation and analysis are key tasks in any data science or data analysis project.
Pandas provides a wide range of functions for data manipulation and analysis, making it easier to
clean, transform and extract insights from data.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('100_Sales_Records.csv')
df.head(5)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.0,6/27/2010,NaN,255.28,159.42,2533654.00,1582243.50,NaN
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480.0,9/15/2012,2804.0,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157.0,5/8/2014,1779.0,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792.0,7/5/2014,8102.0,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712.0,2/6/2013,5062.0,651.21,524.96,3296425.02,2657347.52,639077.50

In [31]:
df.dtypes

Region                str
Country               str
Item Type             str
Sales Channel         str
Order Priority        str
Order Date            str
Order ID          float64
Ship Date             str
Units Sold        float64
Unit Price        float64
Unit Cost         float64
Total Revenue     float64
Total Cost        float64
Total Profit      float64
dtype: object

In [32]:
df.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,9.900000e+01,94.000000,100.000000,100.000000,1.000000e+02,1.000000e+02,9.300000e+01
mean,5.547083e+08,5132.872340,276.761300,191.048000,1.373488e+06,9.318057e+05,4.452835e+05
std,2.619228e+08,2745.135053,235.592241,188.208181,1.460029e+06,1.083938e+06,4.460438e+05
min,1.146066e+08,124.000000,9.330000,6.920000,4.870260e+03,3.612240e+03,1.258020e+03
25%,3.364278e+08,2936.500000,81.730000,35.840000,2.687212e+05,1.688680e+05,1.196850e+05
50%,5.559900e+08,5382.500000,179.880000,107.275000,7.523144e+05,3.635664e+05,2.964483e+05
75%,7.923336e+08,7338.250000,437.200000,263.330000,2.212045e+06,1.613870e+06,6.347459e+05
max,9.940222e+08,9905.000000,668.270000,524.960000,5.997055e+06,4.509794e+06,1.719922e+06

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region          100 non-null    str
 1   Country         100 non-null    str
 2   Item Type       100 non-null    str
 3   Sales Channel   100 non-null    str
 4   Order Priority  100 non-null    str
 5   Order Date      100 non-null    str
 6   Order ID        99 non-null     float64
 7   Ship Date       100 non-null    str
 8   Units Sold      94 non-null     float64
 9   Unit Price      100 non-null    float64
 10  Unit Cost       100 non-null    float64
 11  Total Revenue   100 non-null    float64
 12  Total Cost      100 non-null    float64
 13  Total Profit    93 non-null     float64
dtypes: float64(7), str(7)
memory usage: 11.1 KB

In [ ]:
### Handling Missing Values
df.isnull()
# but at the very first checking all the cells for missing value is not good practice.

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,False,False,False,False,False,False,False,False,True,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
#instead first find if any row or colum has any missing cells.
# isnull().any() by default checks by column, if any column has any missing value it will return True otherwise False
df.isnull().any()

Region            False
Country           False
Item Type         False
Sales Channel     False
Order Priority    False
Order Date        False
Order ID           True
Ship Date         False
Units Sold         True
Unit Price        False
Unit Cost         False
Total Revenue     False
Total Cost        False
Total Profit       True
dtype: bool

In [10]:
df.isnull().any(axis=0) # check by column, if any column has any missing value it will return True otherwise False

Region            False
Country           False
Item Type         False
Sales Channel     False
Order Priority    False
Order Date        False
Order ID           True
Ship Date         False
Units Sold         True
Unit Price        False
Unit Cost         False
Total Revenue     False
Total Cost        False
Total Profit       True
dtype: bool

In [13]:
df.isnull().any(axis=1) # check by row

0      True
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [39]:
# by column how many are missing
df.isnull().sum()

Region            0
Country           0
Item Type         0
Sales Channel     0
Order Priority    0
Order Date        0
Order ID          1
Ship Date         0
Units Sold        6
Unit Price        0
Unit Cost         0
Total Revenue     0
Total Cost        0
Total Profit      7
dtype: int64

In [38]:
# by row how many are missing
df.isnull().sum(axis=1)

0     2
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [ ]:
### fill the missing cells
df_filled = df.fillna(0) # fill the missing cells with 0, and keep a copy of this filled dataframe
df.head(5)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.0,6/27/2010,NaN,255.28,159.42,2533654.00,1582243.50,NaN
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480.0,9/15/2012,2804.0,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157.0,5/8/2014,1779.0,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792.0,7/5/2014,8102.0,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712.0,2/6/2013,5062.0,651.21,524.96,3296425.02,2657347.52,639077.50

In [47]:
df_filled.head(5)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.0,6/27/2010,0.0,255.28,159.42,2533654.00,1582243.50,0.00
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480.0,9/15/2012,2804.0,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157.0,5/8/2014,1779.0,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792.0,7/5/2014,8102.0,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712.0,2/6/2013,5062.0,651.21,524.96,3296425.02,2657347.52,639077.50

In [17]:
df.isnull().sum()
# after filling the missing cells with 0, there are no missing cells in the dataframe, so it will return 0 for all the columns. but i see that there are some missing cells in the 'OrderID' and 'Total Profit'. why ? 

# because the update of the dataframe is not done in place, so the original dataframe is not updated, and the missing cells are still there in the original dataframe. if we want to update the original dataframe then we can use the inplace parameter and set it to True or we can assign the filled dataframe to the original dataframe.

Region            0
Country           0
Item Type         0
Sales Channel     0
Order Priority    0
Order Date        0
Order ID          1
Ship Date         0
Units Sold        6
Unit Price        0
Unit Cost         0
Total Revenue     0
Total Cost        0
Total Profit      7
dtype: int64

In [18]:
df_filled.isnull().sum()

Region            0
Country           0
Item Type         0
Sales Channel     0
Order Priority    0
Order Date        0
Order ID          0
Ship Date         0
Units Sold        0
Unit Price        0
Unit Cost         0
Total Revenue     0
Total Cost        0
Total Profit      0
dtype: int64

In [26]:
### we usually dont put 0 to the missing cells.
# while calculating the mean of the 'Total Profit' column, it will ignore the missing cells and calculate the mean of the available cells, and then we can fill the missing cells with that mean value.
### filling missing cells with the mean of that column.
df['Total Profit_filled'] = df['Total Profit'].fillna(df['Total Profit'].mean())
# a new column 'Total Profit_filled' is created in the dataframe where the missing cells in the 'Total Profit' column are filled with the mean of that column and the rest of the cells are same as the 'Total Profit' column.

In [54]:
df.head(5)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Total Profit_filled
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.0,6/27/2010,NaN,255.28,159.42,2533654.00,1582243.50,NaN,445283.473871
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480.0,9/15/2012,2804.0,205.70,117.11,576782.80,328376.44,248406.36,248406.360000
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157.0,5/8/2014,1779.0,651.21,524.96,1158502.59,933903.84,224598.75,224598.750000
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792.0,7/5/2014,8102.0,9.33,6.92,75591.66,56065.84,19525.82,19525.820000
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712.0,2/6/2013,5062.0,651.21,524.96,3296425.02,2657347.52,639077.50,639077.500000

In [ ]:
df.dtypes

Region                     str
Country                    str
Item Type                  str
Sales Channel              str
Order Priority             str
Order Date                 str
Order ID               float64
Ship Date                  str
Units Sold             float64
Unit Price             float64
Unit Cost              float64
Total Revenue          float64
Total Cost             float64
Total Profit           float64
Total Profit_filled    float64
dtype: object

In [23]:
### Renaming Columns
df_renamed = df.rename(columns={'Order Date':'Ordered Date'}) # it takes a dictionary.
df_renamed.head(6)

,Region,Country,Item Type,Sales Channel,Order Priority,Ordered Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Total Profit_filled
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.0,6/27/2010,NaN,255.28,159.42,2533654.00,1582243.50,NaN,445283.473871
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480.0,9/15/2012,2804.0,205.70,117.11,576782.80,328376.44,248406.36,248406.360000
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157.0,5/8/2014,1779.0,651.21,524.96,1158502.59,933903.84,224598.75,224598.750000
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792.0,7/5/2014,8102.0,9.33,6.92,75591.66,56065.84,19525.82,19525.820000
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712.0,2/6/2013,5062.0,651.21,524.96,3296425.02,2657347.52,639077.50,639077.500000
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2/4/2015,547995746.0,2/21/2015,2974.0,255.28,159.42,759202.72,474115.08,285087.64,285087.640000

In [24]:
### renaming rows
df_renamed = df.rename(index={0:'first row', 1:'second row'})
df_renamed.head(6)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Total Profit_filled
first row,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.0,6/27/2010,NaN,255.28,159.42,2533654.00,1582243.50,NaN,445283.473871
second row,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480.0,9/15/2012,2804.0,205.70,117.11,576782.80,328376.44,248406.36,248406.360000
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157.0,5/8/2014,1779.0,651.21,524.96,1158502.59,933903.84,224598.75,224598.750000
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792.0,7/5/2014,8102.0,9.33,6.92,75591.66,56065.84,19525.82,19525.820000
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712.0,2/6/2013,5062.0,651.21,524.96,3296425.02,2657347.52,639077.50,639077.500000
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2/4/2015,547995746.0,2/21/2015,2974.0,255.28,159.42,759202.72,474115.08,285087.64,285087.640000

In [25]:
### change the datatypes -> .astype()
# full meaning of astype() is as a type.
# object datatypes are basically strings
df['Unit Price_int'] = df['Unit Price'].fillna(df['Unit Price'].mean()).astype(int)

In [27]:
df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Total Profit_filled,Unit Price_int
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.0,6/27/2010,NaN,255.28,159.42,2533654.00,1582243.50,NaN,445283.473871,255
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480.0,9/15/2012,2804.0,205.70,117.11,576782.80,328376.44,248406.36,248406.360000,205
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157.0,5/8/2014,1779.0,651.21,524.96,1158502.59,933903.84,224598.75,224598.750000,651
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792.0,7/5/2014,8102.0,9.33,6.92,75591.66,56065.84,19525.82,19525.820000,9
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712.0,2/6/2013,5062.0,651.21,524.96,3296425.02,2657347.52,639077.50,639077.500000,651

In [ ]:
### appply function to one of the columns
df['Unit Price_int_2x'] = df['Unit Price_int'].apply(lambda x:x*2)
df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Ordered Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Total Profit_filled,Unit Price_int,Unit Price_int_2x
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933.0,6/27/2010,NaN,255.28,159.42,2533654.00,1582243.50,NaN,445283.473871,255,510
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480.0,9/15/2012,2804.0,205.70,117.11,576782.80,328376.44,248406.36,248406.360000,205,410
2,Europe,Russia,Office Supplies,Offline,L,5/2/2014,341417157.0,5/8/2014,1779.0,651.21,524.96,1158502.59,933903.84,224598.75,224598.750000,651,1302
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792.0,7/5/2014,8102.0,9.33,6.92,75591.66,56065.84,19525.82,19525.820000,9,18
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2/1/2013,115456712.0,2/6/2013,5062.0,651.21,524.96,3296425.02,2657347.52,639077.50,639077.500000,651,1302

In [ ]:
### Data Aggregating and Grouping 
# aggregation:
# summarizing data into a single value.
# e.g. sum,mean, of a total column. df['Marks'].mean()

# Grouping:
# groupby() is used to group the data based on some column, and then we can apply some aggregation function on that grouped data. It creates unique values of those column and then apply the aggregation function on that unique values.
# e.g. df.groupby('Dept')

In [28]:
# combining this two
# df.groupby('Dept')['Marks'].mean()
grouped_max = df.groupby('Item Type')['Unit Price_int'].max()
# this will group the data by 'Item Type' and then it will calculate the maximum value of 'Unit Price_int' for each group and return a new dataframe with 'Item Type' as index and 'Unit Price_int' as column.
print(grouped_max)

Item Type
Baby Food          255
Beverages           47
Cereal             205
Clothes            109
Cosmetics          437
Fruits               9
Household          668
Meat               421
Office Supplies    651
Personal Care       81
Snacks             152
Vegetables         154
Name: Unit Price_int, dtype: int64

In [ ]:
### multiple grouping
two_group = df.groupby(['Item Type', 'Country'])['Unit Price_int'].sum()
print(two_group)

Item Type   Country
Baby Food   Monaco             255
            Norway             255
            Portugal           255
            San Marino         255
            Solomon Islands    255
                              ...
Vegetables  Kenya              154
            Kyrgyzstan         154
            Laos               154
            Sierra Leone       154
            Slovakia           154
Name: Unit Price_int, Length: 97, dtype: int64

In [ ]:
two_group = df.groupby(['Country','Item Type'])['Unit Price_int'].sum()
print(two_group)

Country         Item Type
Albania         Clothes            109
Angola          Household          668
Australia       Beverages           47
                Cereal             205
                Office Supplies    651
                                  ...
Turkmenistan    Household          668
                Office Supplies    651
Tuvalu          Baby Food          255
United Kingdom  Household          668
Zambia          Snacks             152
Name: Unit Price_int, Length: 97, dtype: int64

In [ ]:
whats the difference between these two groupings ?
Think of it like folders

groupby(['Item Type', 'Country'])
Fruit/
    Canada
    USA

Vegetable/
    USA

groupby(['Country', 'Item Type'])
Canada/
    Fruit

USA/
    Fruit
    Vegetable

The underlying records in each group are the same, but the hierarchy (MultiIndex structure) is different.

In [74]:
### multiple aggregate func:
mult_aggre = df.groupby('Item Type')['Unit Price_int'].agg(['mean','sum','count'])
mult_aggre

                  mean   sum  count
Item Type
Baby Food        255.0  1785      7
Beverages         47.0   376      8
Cereal           205.0  1435      7
Clothes          109.0  1417     13
Cosmetics        437.0  5681     13
Fruits             9.0    90     10
Household        668.0  6012      9
Meat             421.0   842      2
Office Supplies  651.0  7812     12
Personal Care     81.0   810     10
Snacks           152.0   456      3
Vegetables       154.0   924      6

In [3]:
### Merging and Joining Dataframes
# Create sample DataFrames
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [6]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [5]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [7]:
pd.merge(df1, df2, on='Key', how='inner') # inner join will return only the common keys in both dataframes.

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [8]:
pd.merge(df1, df2, on='Key', how='outer') # outer join will return all the keys from both dataframes, and if there is no match then it will return NaN.

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [9]:
pd.merge(df1, df2, on='Key', how='left') # left join will return all the keys from the left dataframe (df1) and the matching keys from the right dataframe (df2). If there is no match, it will return NaN for the columns from the right dataframe.

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [10]:
pd.merge(df1, df2, on='Key', how='right') # right join will return all the keys from the right dataframe (df2) and the matching keys from the left dataframe (df1). If there is no match, it will return NaN for the columns from the left dataframe.

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6